config/routes.rb
Rails.application.routes.draw do
  get 'founds/search_results',to:'founds#search_results'
  resources :users
  resources :losts
  resources :founds
  root 'founds#index'

end

app/models/found.rb
class Found < ActiveRecord::Base
  belongs_to :user

  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/lost.rb
class Lost < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :losts
  has_many :founds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all

end

app/controllers/founds_controller.rb
class FoundsController < ApplicationController

  def index
    @found_items = Found.all
  end

  def search_results

    search = params[:search]
    found_items = Found.all

    @matches = {}

    found_items.each do |item|
        @matches[item] = get_str_cosine(search, item.description)
      end

      @matches = @matches.sort_by {|_key, value| value}.reverse

  end


  def show
    @found_item = Found.find(params[:id])
  end

  def found_search
    #POST
    @found_items = Found.where()
  end


  def new
    #Form for new found item
  end

  def create
    #POST to create new found item
    @found_item = Found.new(found_params)
    if @found_item.save
      redirect_to root_path
    else

    end
  end

  private
  def found_params
    params.require(:founds).permit(:user_id, :title, :brand, :category, :kind, :color, :description, :location, :photo)
  end
end

app/controllers/losts_controller.rb
include ApplicationHelper

class LostsController < ApplicationController

  def index
    @lost_items = Lost.all
  end

  def show
    lost_item = Lost.find(params[:id])
    found_items = Found.all

    @matches = []
    @score = {}
    found_items.each do |found_item|
      if lost_item.category == found_item.category
        @score[found_item] = 0
        if lost_item.brand == found_item.brand
          @score[found_item] += 1
        end
        if lost_item.color == found_item.color
          @score[found_item] += 0.5
        end
        if lost_item.kind == found_item.kind
          @score[found_item] += 0.75
        end
        @score[found_item] += get_str_cosine(lost_item.description, found_item.description)
      end
    end
    @score = @score.sort_by {|_key, value| value}.reverse
  end

  def new
    @lost = Lost.new()
  end

  def create
    @lost_item = Lost.new(lost_params)
    if @lost_item.save
      redirect_to losts_path
    else

    end
  end

  private
  def lost_params
    params.require(:lost_item).permit(:user_id, :title, :brand, :category, :kind, :color, :description, :location, :photo, :reward)
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def clean_description(string)
  string = string.downcase
  conjunctions = ["for", "and","so", "nor", "but", "or", "yet" ]
  useless_words = ["he", "she", "him ","it", "her", "them", "my", "his", "their", "at", "it's", "on" ,"with", "like", "as", "to", "also", "then", "again" ]

  conjunctions.each do |word|
    string = string.sub(/\b#{word}\b/,'')
  end

  useless_words.each do |word|
    string = string.sub(/\b#{word}\b/,'')
  end
  return string
end

def word_hash(arr)
  hash = {}
  arr.each do |word|
    if hash[word]
      hash[word] += 1
    else
      hash[word] = 1
    end
  end
  return hash
end


def extract_word_vec(string)
  word = string.scan(/\w{2,}/)
  p word
  return word_hash(word)
end

def get_cosine(vec_1, vec_2)
  intersection = Set.new(vec_1.keys) & Set.new(vec_2.keys)
  numerator = 0
  intersection.each do |key|
    numerator += vec_1[key] * vec_2[key]
  end

  sum1 = 0
  vec_1.each do |key, value|
    sum1 += (value**2)
  end

  sum2 = 0
  vec_2.each do |key, value|
    sum2 += (value**2)
  end

  denominator = Math.sqrt(sum1) * Math.sqrt(sum2)

  if denominator == 0
    return 0
  else
    return numerator.to_f/denominator.to_f
  end

end


def get_str_cosine(str1, str2)
  h1 = extract_word_vec(clean_description(str1))
  h2 = extract_word_vec(clean_description(str2))

  return get_cosine(h1, h2)

end
end

app/views/found/_form.html.erb
<%= form_for :founds, html: { :multipart => true }, url: { action: "create"} do |f| %>
<p>
<%= f.label :title %>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :description %>
<%= f.text_field :description %>
</p>
<p>
<%= f.file_field :photo%>
</p>
<p>
<%= f.submit "Submit" %>
</p>
<% end %>

app/views/found/new.html.erb
<h1>New Found Item</h1>

<%= render partial: 'form' %>

app/views/found/new.html.haml
.container-fluid
  .row
    .col-sm-12
      = link_to 'Back', admin_index_path, class: 'btn btn-success admin-buttons pull-right'
.container
  .row
    .col-lg-12
      = form_for @found, html: { class: 'form-horizontal center', id: 'found-form' } do |f|
        %img.macrabz-admin.center-block{:alt => 'Macrabz Emporium', :src => '/assets/amacrabz-f090c51c8aa06149fcc20cb1c563d771075b1e63998352663694b5c9bd55ffb4.svg'}
        %h1.text-center.edit-header
          Add Found
        .form-center
          - if flash[:error]
            #flash.error.text-center
              = flash[:error]
          .form-group
            = f.label :image, 'Image url:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :image, class: 'form-control'
          .form-group
            = f.label :title, 'Title:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :description, 'Description:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_area :description, class: 'form-control'
          .form-group
            = f.label :location, 'Location:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :location, class: 'form-control'
          .form-group
            = f.label :brand, 'Brand:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :brand, class: 'form-control'
          .form-group
            = f.label :colors, 'Colors:', class: 'col-lg-4 control-label'
            .col-md-8
              .dropdown
                %button#dropdownColors.btn.btn-default.dropdown-toggle{ 'aria-expanded' => true, 'aria-haspopup' => true, 'data-toggle' => 'dropdown', type: 'button' }
                  %span.hida.caret
                  %p.multiSel
                %ul.dropdown-menu{'aria-labelledby' => 'dropdownCategories'}
                  %ul.multiSelect{multiple: 'multiple'}
                    - @colors.each do |color|
                      %li
                        %input{type: 'checkbox', value: category.id, name: 'category_ids[]'}
                        = color.name
          .col-md-12.update-button
            = f.submit 'Add Found Item', class: 'btn btn-primary btn-lg center-block'

app/views/found/show.html.erb
<%= image_tag @found.photo.url(:small) %>

app/views/founds/index.html.haml
.container
  .row
    .col-sm-12
      %img.checkout-image.center-block{:alt => 'foundit', :src => '/assets/founditlogo2.png'}
      %br
      %br
      %form{action:"/founds/search_results"}
        .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
          .input-group
            %span.input-group-btn
              %button.btn.btn-default{:type => "submit"} Let's find your missing item!
            %input.form-control{:placeholder => "Search for...", :type => "text", name:"search"}
        %table#cart.table
          %thead
            %tr
              %br
              %br
              %br
              %br
              %th.text-center Title
              %th.text-center Description
              %th.text-center Location
              %th.text-center Category
              %th.text-center Type
              %th.text-center Color
              %th.text-center Brand
          %tbody
          - @found_items.each do |item|
            %tr
              %td.text-center= item.title
              %td.text-center= item.description
              %td.text-center= item.location
              %td.text-center= item.category
              %td.text-center= item.kind
              %td.text-center= item.color
              %td.text-center= item.brand

app/views/founds/new.html.haml
.container-fluid
.container
  .row
    .col-lg-12.col-md-12
      = form_for :founds, html: { multipart: true, class: 'form-horizontal center', id: 'found-form' }, url: { action: "create"} do |f|
        %img.macrabz-admin.center-block{:alt => 'foundit', :src => '/assets/founditlogo.png'}
          .form-group
            = f.label :photo, 'Picture:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.file_field :photo, class: 'col-lg-4 control-label'
          .form-group
            = f.label :title, 'Title:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :category, 'Category:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :category, class: 'form-control'
          .form-group
            = f.label :kind, 'Type:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :kind, class: 'form-control'
          .form-group
            = f.label :color, 'Color(s):', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :color, class: 'form-control'
          .form-group
            = f.label :description, 'Description:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_area :description, class: 'form-control'
          .form-group
            = f.label :location, 'Location:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :location, class: 'form-control'
          .form-group
            = f.label :brand, 'Brand:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :brand, class: 'form-control'
          .col-md-12.update-button
            = f.submit 'Add Found Item', class: 'btn btn-primary btn-lg center-block'
          %br
          %br
          %br
          %br
      %hr

app/views/founds/search_results.html.haml
.container
  .row
    .col-sm-12
      %img.checkout-image.center-block{:alt => 'foundit', :src => '/assets/founditlogo2.png'}
      %h1.text-center.index-header Found Items
      %form
        .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
          .input-group
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"} Lets Find It!
            %input.form-control{:placeholder => "Search for...", :type => "text"}
        %table#cart.table
          %thead
            %tr

              %th.text-center Title
              %th.text-center Score
              %th.text-center Description
              %th.text-center Location
              %th.text-center Brand
              %th.text-center Date
          %tbody
          - @matches.each do |item, score|
            %tr

              %td.text-center
                %a{href:"/founds/#{item.id}"}= item.title
                %td.text-center= score.round(2)
              %td.text-center= item.description
              %td.text-center= item.location
              %td.text-center= item.brand
              %td.text-center= item.created_at

app/views/founds/show.html.haml
.container
  .row
    .col-lg-12
      .col-lg-7
        %h1.product-page-header.text-center= image_tag(@found_item.photo)
        %h1.product-page-header.text-center= @found_item.title
        %p.product-page-desc.text-center= @found_item.description
        %p.product-page-desc.text-center= @found_item.color
        %p.product-page-desc.text-center= @found_item.brand
        %p.product-page-desc.text-center
          Found At:
          = @found_item.location

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Lostandfound
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => ".navbar-brand", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to image_tag('/assets/founditlogo2.png'), losts_path, class: 'navbar-brand'
      .collapse.navbar-collapse#main-nav
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Lost
              %b.caret
            %ul.dropdown-menu{ :role => 'menu'}
              %li
                = link_to 'View all Lost Items', losts_path
                = link_to 'Add a Lost Item', new_lost_path
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Found
              %b.caret
            %ul.dropdown-menu{ :role => 'menu'}
              %li
                = link_to 'View all Found Items', founds_path
                = link_to 'Add a Found Item', new_found_path
        = link_to image_tag('/assets/search2.png'), losts_path, class: 'navbar-search slideout-menu-toggle'
  %body
    .container
      .row
        .col-sm-12
          %p.notice.text-center= notice
          %p.alert.text-center= alert
    = yield
    .slideout-menu
      %h3
        .statisticstitle
      .row
        .col-lg-8.col-lg-offset-2
          %form
            %input.form-control{:placeholder => "Item", :type => "text"}
            %br
            %input.form-control{:placeholder => "Description", :type => "text"}
            %br
            %input.form-control{:placeholder => "Location", :type => "text"}
            %br
            %input.form-control{:placeholder => "Date", :type => "text"}
            %br
            %ul.nav.navbar-nav
              %li.dropdown
                %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  Color
                  %b.caret
                %ul.dropdown-menu{ :role => 'menu'}
                  %li
                    Yellow
                  %li
                    Orange
                  %li
                    Green
                  %li
                    Blue
            %br
            %br
            %br
              %ul.nav.navbar-nav
                %li.dropdown
                  %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    Lost or Found?
                    %b.caret
                  %ul.dropdown-menu{ :role => 'menu'}
                    %li
                      Lost
                    %li
                      Found
            %br
            %button.update-button.btn.btn-primary.btn-lg.center-block
              Search

app/views/lost/new.html.haml
.container-fluid
  .row
    .col-sm-12
      = link_to 'Back', admin_index_path, class: 'btn btn-success admin-buttons pull-right'
.container
  .row
    .col-lg-12
      = form_for @found, html: { class: 'form-horizontal center', id: 'found-form' } do |f|
        %img.macrabz-admin.center-block{:alt => 'Macrabz Emporium', :src => '/assets/amacrabz-f090c51c8aa06149fcc20cb1c563d771075b1e63998352663694b5c9bd55ffb4.svg'}
        %h1.text-center.edit-header
          Add Found
        .form-center
          - if flash[:error]
            #flash.error.text-center
              = flash[:error]
          .form-group
            = f.label :image, 'Image url:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :image, class: 'form-control'
          .form-group
            = f.label :title, 'Title:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :description, 'Description:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_area :description, class: 'form-control'
          .form-group
            = f.label :location, 'Location:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :location, class: 'form-control'
          .form-group
            = f.label :brand, 'Brand:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :brand, class: 'form-control'
          .form-group
            = f.label :colors, 'Colors:', class: 'col-lg-4 control-label'
            .col-md-8
              .dropdown
                %button#dropdownColors.btn.btn-default.dropdown-toggle{ 'aria-expanded' => true, 'aria-haspopup' => true, 'data-toggle' => 'dropdown', type: 'button' }
                  %span.hida.caret
                  %p.multiSel
                %ul.dropdown-menu{'aria-labelledby' => 'dropdownCategories'}
                  %ul.multiSelect{multiple: 'multiple'}
                    - @colors.each do |color|
                      %li
                        %input{type: 'checkbox', value: category.id, name: 'category_ids[]'}
                        = color.name
           .form-group
            = f.label :reward, 'Reward:', class: 'col-lg-4 control-label'
            .col-md-8
              = f.text_field :reward, class: 'form-control'
          .col-md-12.update-button
            = f.submit 'Add Found Item', class: 'btn btn-primary btn-lg center-block'

app/views/losts/index.html.haml
.container
  .row
    .col-sm-12
      %img.checkout-image.center-block{:alt => 'foundit', :src => '/assets/lostit.png'}
      %br
      %br
      %form{action:"/founds/search_results"}
        .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-2
          .input-group
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"} Help return someone's missing item!
            %input.form-control{:placeholder => "Search for...", :type => "text", name:"search"}
        %table#cart.table
          %thead
            %tr
              %br
              %br
              %br
              %br

              %th.text-center Title
              %th.text-center Description
              %th.text-center Location
              %th.text-center Category
              %th.text-center Type
              %th.text-center Color
              %th.text-center Brand
              %th.text-center Reward
          %tbody
          - @lost_items.each do |item|
            %tr

              %td.text-center= item.title
              %td.text-center= item.description
              %td.text-center= item.location
              %td.text-center= item.category
              %td.text-center= item.kind
              %td.text-center= item.color
              %td.text-center= item.brand
              %th.text-center= item.reward
      %br

app/views/losts/matches.html.haml
.container-fluid
  .row
    .col-sm-12
      = link_to new_product_path, class: 'btn btn-success admin-buttons pull-right' do
        %i.glyphicon.glyphicon-plus
        %span Add Product
.container
  .row
    .col-sm-12
      = link_to image_tag('/assets/founditlogo.png'), index_path, class: 'macrabz-admin center-block'
      %h1.text-center.index-header Your Inventory!
      - if flash[:success]
        #flash.success.text-center
          = flash[:success]
      %table.table.table-striped
        %thead
          %tr
            %th
            %th Picture
            %th.text-center Description
        %tbody
          - @matches.each do |match|
            %tr
              %td.clickable-row.admin-image{'data-url' => "/products/#{match.id}"}= image_tag(match.picture)
              %td.clickable-row{'data-url' => "/products/#{match.id}"}= match.description

app/views/losts/new.html.haml
.container-fluid
.container
  .row
    .col-md-12.col-lg-12
      = form_for :lost_item, html: { multipart: true, class: 'form-horizontal center', id: 'lost-form' }, url: { action: "create"} do |f|
        %img.macrabz-admin.center-block{:alt => 'foundit', :src => '/assets/lostit.png'}
        .form-center
          - if flash[:error]
            #flash.error.text-center
              = flash[:error]
          .form-group
            = f.label :photo, 'Picture:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.file_field :photo, class: 'col-lg-4 control-label'
          .form-group
            = f.label :title, 'Title:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :title, class: 'form-control'
          .form-group
            = f.label :category, 'Category:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :category, class: 'form-control'
          .form-group
            = f.label :kind, 'Type:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :kind, class: 'form-control'
          .form-group
            = f.label :color, 'Color(s):', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :color, class: 'form-control'
          .form-group
            = f.label :description, 'Description:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_area :description, class: 'form-control'
          .form-group
            = f.label :location, 'Location:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :location, class: 'form-control'
          .form-group
            = f.label :brand, 'Brand:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.text_field :brand, class: 'form-control'
          .form-group
            = f.label :reward, 'Reward:', class: 'col-lg-2 control-label'
            .col-md-8
              = f.number_field :reward, class: 'form-control'
          .col-md-12.update-button
            = f.submit 'Add Lost Item', class: 'btn btn-primary btn-lg center-block'
          %br
          %br
          %br
          %br
      %hr

app/views/losts/show.html.haml
.container
  .row
    .col-lg-12
      .col-lg-7
      = @score.each do |found_item, score|
        %h1.product-page-header.text-center
          %a{href:"/founds/#{found_item.id}"}= found_item.title
        %p.product-page-header.text-center
          Category
          = found_item.category
        %p.product-page-header.text-center
          = found_item.kind
        %p.product-page-header.text-center
          = found_item.color
        %p.product-page-header.text-center
          = found_item.description
        %p.product-page-desc.text-center
          = score